package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2021-JAN-03  11:31:17 AM
 */
public class phraseEng extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(64);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: NOVOICE
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "NOVOICE", "NOVOICE.wav", ""); 

		// phrase: PASSPHRASE
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "PASSPHRASE", "PASSPHRASE.wav", ""); 

		// phrase: VBPASS
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "VBPASS", "VBPASS.wav", ""); 

		// phrase: MAX_RETRY
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "MAX_RETRY", "MAX_RETRY.wav", ""); 

		// phrase: VB_NOTVALIDPHRASE
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "VB_NOTVALIDPHRASE", "VB_NOTVALIDPHRASE.wav", ""); 

		// phrase: VB_ENROL_005
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "VB_ENROL_005", "VB_ENROL_005.wav", ""); 

		// phrase: VB_VOICEPLAY
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "VB_VOICEPLAY", "VB_VOICEPLAY.wav", ""); 

		// phrase: RECORD_PRINT2
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "RECORD_PRINT2", "RECORD_PRINT2.wav", ""); 

		// phrase: technicalError
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "technicalError", "technicalError.wav", ""); 

		// phrase: SPEAKTOAGENT
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "SPEAKTOAGENT", "SPEAKTOAGENT.wav", ""); 

		// phrase: inConclusiveMaxRetries
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "inConclusiveMaxRetries", "inConclusiveMaxRetries.wav", ""); 

		// phrase: TO_OPT_OUT
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "TO_OPT_OUT", "TO_OPT_OUT.wav", ""); 

		// phrase: VB_DEREG_SUCC
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "VB_DEREG_SUCC", "VB_DEREG_SUCC.wav", ""); 

		// phrase: VB_UNBLOCK_SUCC
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "VB_UNBLOCK_SUCC", "VB_UNBLOCK_SUCC.wav", ""); 

		// phrase: THREESAMPLES
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "THREESAMPLES", "THREESAMPLES.wav", ""); 

		// phrase: NO_INPUT_001
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "NO_INPUT_001", "NO_INPUT_001.wav", ""); 

		// phrase: ANC_RETRY_02
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "ANC_RETRY_02", "ANC_RETRY_02.wav", ""); 

		// phrase: RECORD_PRINT1
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "RECORD_PRINT1", "RECORD_PRINT1.wav", ""); 

		// phrase: CONT_SER
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "CONT_SER", "CONT_SER.wav", ""); 

		// phrase: ANC_RETRY_01
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "ANC_RETRY_01", "ANC_RETRY_01.wav", ""); 

		// phrase: INVALID_INPUT_001
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "INVALID_INPUT_001", "INVALID_INPUT_001.wav", ""); 

		// phrase: MAX_RETRY_001
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "MAX_RETRY_001", "MAX_RETRY_001.wav", ""); 

		// phrase: ANC_RETRY_03
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "ANC_RETRY_03", "ANC_RETRY_03.wav", ""); 

		// phrase: VB_VOICENOTRECOG
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "VB_VOICENOTRECOG", "VB_VOICENOTRECOG.wav", ""); 

		// phrase: Press0
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "Press0", "Press0.wav", ""); 

		// phrase: Press1
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "Press1", "Press1.wav", ""); 

		// phrase: Press2
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "Press2", "Press2.wav", ""); 

		// phrase: VB_ENROLLFAILURE
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "VB_ENROLLFAILURE", "VB_ENROLLFAILURE.wav", ""); 

		// phrase: HOST_FAIL_001
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "HOST_FAIL_001", "HOST_FAIL_001.wav", ""); 

		// phrase: ELSE
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "ELSE", "ELSE.wav", ""); 

		// phrase: OPT_OUT_CONFIRM
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "OPT_OUT_CONFIRM", "OPT_OUT_CONFIRM.wav", ""); 

		// phrase: MAX_RETRY_002
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.phraseEng.urlbase", "MAX_RETRY_002", "MAX_RETRY_002.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024-MAR-29  10:23:34 AM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(phraseEng.PHRASE_MAP, phraseName));
	}
}
