package flow;

/**
 * This interface is used to define the name of variables that are 
 * declared in the call flow.  All variables are defined as 
 * <code>public static final String</code>, which allows user-defined
 * code to reference variable names by the Java variable name.
 * Last generated by Orchestration Designer at: 2021-JUN-06  03:33:18 PM
 */
public interface IProjectVariables {





	//{{START:PROJECT:VARIABLES
	/**
	 * This is a reserved block of variable name definitions.
	 * The variable names defined here can be used as the key
	 * to get the <code>com.avaya.sce.runtime.Variable</code>
	 * from the <code>SCESession</code> at runtime.<br>
	 * 
	 * For example, given a variable name <code>phoneNum</code>,
	 * user-defined code should access the variable in this format:<PRE>
	 *   Variable phNum = mySession.getVariable(IProjectVariables.PHONE_NUM);
	 *   if ( phNum != null ) {
	 *        // do something with the variable
	 *   }</PRE>
	 * 
	 * This block of code is generated automatically by Orchestration Designer and should not
	 * be manually edited as changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2024-MAR-29  10:24:21 AM
	 */
	public static final String RESPONSE_CODE = "responseCode";
	public static final String DYNAMIC_PC = "DynamicPC";
	public static final String CONNECTBACK = "connectback";
	public static final String METHOD = "Method";
	public static final String PHRASEVAR = "phrasevar";
	public static final String REDIRECTINFO = "redirectinfo";
	public static final String IS_PROPERTY_FILE_MODIFIED = "IsPropertyFileModified";
	public static final String IS_VBHISTORY_INSERTED = "IsVBHistoryInserted";
	public static final String CONTEXT = "Context";
	public static final String IS_ENABLED = "IsEnabled";
	public static final String CONSENT_MENU = "consentMenu";
	public static final String VBSTATUSDATE = "vbstatusdate";
	public static final String AUTHENTICATE_VOICE_PC = "authenticateVoicePC";
	public static final String POST__CALIBRATION = "POST_CALIBRATION";
	public static final String CHECK_CONTEXT = "checkContext";
	public static final String VC__TRANSFERRED__BY__AGENT__ROLE = "VC_TRANSFERRED_BY_AGENT_ROLE";
	public static final String START_SESSION_WS = "startSessionWS";
	public static final String VBSTATUSCODE = "vbstatuscode";
	public static final String CUSTOMERDETAILS = "customerdetails";
	public static final String SESSION = "session";
	public static final String CONTEXTID = "contextid";
	public static final String ERROR_COUNT = "ErrorCount";
	public static final String TIMEOUT = "timeout";
	public static final String TRANSFER_VDN = "TransferVDN";
	public static final String RETRY = "retry";
	public static final String AUTHENTICATE_VOICE = "authenticateVoice";
	public static final String SET_APPLICATION_STATUS_WS = "setApplicationStatusWS";
	public static final String DD_LAST_EXCEPTION = "ddLastException";
	public static final String EXIT_MENU = "ExitMenu";
	public static final String VC__TRANSFERRED__BY__AGENT__ID = "VC_TRANSFERRED_BY_AGENT_ID";
	public static final String TIME = "time";
	public static final String DATEFORMAT = "dateformat";
	public static final String SHAREDUUI = "shareduui";
	public static final String ENROLLFAILED = "enrollfailed";
	public static final String ENROLLMENT_STATUS = "EnrollmentStatus";
	public static final String PREPARED_UUI = "PreparedUUI";
	public static final String VBSTATUS = "vbstatus";
	public static final String VB_CONTEXT_STORE = "vbContextStore";
	public static final String REJECTDAYS = "rejectdays";
	public static final String NUANCEMETHOD = "nuancemethod";
	public static final String DYNAMIC_MENU_VAR = "DynamicMenuVar";
	public static final String ENROLLMAXTRIES = "enrollmaxtries";
	public static final String BLIND_TRANSFER = "BlindTransfer";
	public static final String ENROLL_WS = "EnrollWS";
	public static final String TRAIN_WS = "TrainWS";
	public static final String VERIFY = "verify";
	public static final String NUANCE_SERVER_STATE = "NuanceServerState";
	public static final String ENROLL_VOICE_PC = "enrollVoicePc";
	public static final String VB_INPUTS = "vbInputs";
	public static final String AUTHENTICATE_WS = "AuthenticateWS";
	public static final String DATE = "date";
	public static final String HASH_MAP = "HashMap";
	public static final String IS_EXTENSION_TRANSFER = "isExtensionTransfer";
	public static final String UUI = "UUI";
	public static final String SERVICEMAP = "servicemap";
	public static final String DEENROLLDAYS = "deenrolldays";
	public static final String VBREASON = "vbreason";
	public static final String VBSELFSERVE = "vbselfserve";
	public static final String VC__WORK__REQUEST__ID = "VC_WORK_REQUEST_ID";
	public static final String PROPERTY_FILE_LOCATION = "PropertyFileLocation";
	public static final String ENROLLREJECT = "enrollreject";
	public static final String IS_CALL_HISTORY_INSERTED = "isCallHistoryInserted";
	public static final String DYNAMIC_MENU = "DynamicMenu";
	public static final String ERROR = "Error";
	public static final String ENROLLMENU = "enrollmenu";
	//}}END:PROJECT:VARIABLES
	//{{START:PROJECT:VARIABLEFIELDS
	public static final String DYNAMIC_PC_FIELD_CONFIDENCE = "confidence";
	public static final String DYNAMIC_PC_FIELD_INPUTMODE = "inputmode";
	public static final String DYNAMIC_PC_FIELD_INTERPRETATION = "interpretation";
	public static final String DYNAMIC_PC_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String DYNAMIC_PC_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String DYNAMIC_PC_FIELD_UTTERANCE = "utterance";
	public static final String DYNAMIC_PC_FIELD_VALUE = "value";
	public static final String PHRASEVAR_FIELD_PH_1 = "ph1";
	public static final String PHRASEVAR_FIELD_PH_2 = "ph2";
	public static final String PHRASEVAR_FIELD_PH_3 = "ph3";
	public static final String PHRASEVAR_FIELD_PH_4 = "ph4";
	public static final String PHRASEVAR_FIELD_PH_5 = "ph5";
	public static final String PHRASEVAR_FIELD_PH_6 = "ph6";
	public static final String PHRASEVAR_FIELD_PH_7 = "ph7";
	public static final String PHRASEVAR_FIELD_PH_8 = "ph8";
	public static final String REDIRECTINFO_FIELD_PRESENTATIONINFO = "presentationinfo";
	public static final String REDIRECTINFO_FIELD_REASON = "reason";
	public static final String REDIRECTINFO_FIELD_SCREENINGINFO = "screeninginfo";
	public static final String REDIRECTINFO_FIELD_URI = "uri";
	public static final String CONTEXT_FIELD_CONTEXT_ID = "ContextId";
	public static final String CONTEXT_FIELD_INTENT = "intent";
	public static final String CONTEXT_FIELD_SERVICE__LOB = "Service_LOB";
	public static final String CONTEXT_FIELD_SERVICE_MAP = "ServiceMap";
	public static final String CONTEXT_FIELD_TRF = "trf";
	public static final String CONSENT_MENU_FIELD_CONFIDENCE = "confidence";
	public static final String CONSENT_MENU_FIELD_INPUTMODE = "inputmode";
	public static final String CONSENT_MENU_FIELD_INTERPRETATION = "interpretation";
	public static final String CONSENT_MENU_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String CONSENT_MENU_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String CONSENT_MENU_FIELD_UTTERANCE = "utterance";
	public static final String CONSENT_MENU_FIELD_VALUE = "value";
	public static final String AUTHENTICATE_VOICE_PC_FIELD_CONFIDENCE = "confidence";
	public static final String AUTHENTICATE_VOICE_PC_FIELD_DURATION = "duration";
	public static final String AUTHENTICATE_VOICE_PC_FIELD_MAXTIME = "maxtime";
	public static final String AUTHENTICATE_VOICE_PC_FIELD_SIZE = "size";
	public static final String AUTHENTICATE_VOICE_PC_FIELD_TERMCHAR = "termchar";
	public static final String AUTHENTICATE_VOICE_PC_FIELD_UTTERANCE = "utterance";
	public static final String AUTHENTICATE_VOICE_PC_FIELD_VALUE = "value";
	public static final String START_SESSION_WS_FIELD_EXCEPTION = "exception";
	public static final String START_SESSION_WS_FIELD_SESSION_ID = "sessionId";
	public static final String CUSTOMERDETAILS_FIELD_COUNTRYCODE = "countrycode";
	public static final String CUSTOMERDETAILS_FIELD_DO_B = "DoB";
	public static final String CUSTOMERDETAILS_FIELD_EMAIL = "email";
	public static final String CUSTOMERDETAILS_FIELD_FFPNUMBER = "ffpnumber";
	public static final String CUSTOMERDETAILS_FIELD_MEMBERTIER = "membertier";
	public static final String CUSTOMERDETAILS_FIELD_MOBILE = "mobile";
	public static final String CUSTOMERDETAILS_FIELD_NAME = "name";
	public static final String CUSTOMERDETAILS_FIELD_SEGMENT = "segment";
	public static final String SESSION_FIELD_AAI = "aai";
	public static final String SESSION_FIELD_ANI = "ani";
	public static final String SESSION_FIELD_CALLTAG = "calltag";
	public static final String SESSION_FIELD_CHANNEL = "channel";
	public static final String SESSION_FIELD_CHANNELTYPE = "channeltype";
	public static final String SESSION_FIELD_CONVERSEFIRST = "conversefirst";
	public static final String SESSION_FIELD_CONVERSESECOND = "conversesecond";
	public static final String SESSION_FIELD_CURRENTLANGUAGE = "currentlanguage";
	public static final String SESSION_FIELD_DNIS = "dnis";
	public static final String SESSION_FIELD_EXIT_CUSTOMER_ID = "exitCustomerId";
	public static final String SESSION_FIELD_EXIT_INFO_1 = "exitInfo1";
	public static final String SESSION_FIELD_EXIT_INFO_2 = "exitInfo2";
	public static final String SESSION_FIELD_EXIT_PARENT_ID = "exitParentId";
	public static final String SESSION_FIELD_EXIT_PREFERRED_PATH = "exitPreferredPath";
	public static final String SESSION_FIELD_EXIT_REASON = "exitReason";
	public static final String SESSION_FIELD_EXIT_TOPIC = "exitTopic";
	public static final String SESSION_FIELD_LASTERROR = "lasterror";
	public static final String SESSION_FIELD_MEDIATYPE = "mediatype";
	public static final String SESSION_FIELD_PROTOCOLNAME = "protocolname";
	public static final String SESSION_FIELD_PROTOCOLVERSION = "protocolversion";
	public static final String SESSION_FIELD_SESSIONID = "sessionid";
	public static final String SESSION_FIELD_SESSIONLABEL = "sessionlabel";
	public static final String SESSION_FIELD_SHAREDMODE = "sharedmode";
	public static final String SESSION_FIELD_UCID = "ucid";
	public static final String SESSION_FIELD_UUI = "uui";
	public static final String SESSION_FIELD_VIDEOBITRATE = "videobitrate";
	public static final String SESSION_FIELD_VIDEOCODEC = "videocodec";
	public static final String SESSION_FIELD_VIDEOENABLED = "videoenabled";
	public static final String SESSION_FIELD_VIDEOFARFMTP = "videofarfmtp";
	public static final String SESSION_FIELD_VIDEOFORMAT = "videoformat";
	public static final String SESSION_FIELD_VIDEOFPS = "videofps";
	public static final String SESSION_FIELD_VIDEOHEIGHT = "videoheight";
	public static final String SESSION_FIELD_VIDEONEARFMTP = "videonearfmtp";
	public static final String SESSION_FIELD_VIDEOWIDTH = "videowidth";
	public static final String SESSION_FIELD_VPCALLEDEXTENSION = "vpcalledextension";
	public static final String SESSION_FIELD_VPCONVERSEONDATA = "vpconverseondata";
	public static final String SESSION_FIELD_VPCOVERAGEREASON = "vpcoveragereason";
	public static final String SESSION_FIELD_VPCOVERAGETYPE = "vpcoveragetype";
	public static final String SESSION_FIELD_VPRDNIS = "vprdnis";
	public static final String SESSION_FIELD_VPREPORTURL = "vpreporturl";
	public static final String RETRY_FIELD_ACC__CONFIRM__RETRY = "acc_confirm_retry";
	public static final String RETRY_FIELD_ACC__NOT__MATCH__RETRY = "acc_not_match_retry";
	public static final String RETRY_FIELD_AST__COUNT = "ast_count";
	public static final String RETRY_FIELD_CALL_LOG__NO_INPUT_COUNT = "CallLog_noInputCount";
	public static final String RETRY_FIELD_CALL_LOG__NO_MATCH_COUNT = "CallLog_noMatchCount";
	public static final String RETRY_FIELD_CC__NOT__MATCH__RETRY = "cc_not_match_retry";
	public static final String RETRY_FIELD_COUNT = "count";
	public static final String RETRY_FIELD_CVV__NM__RETRY = "cvv_NM_retry";
	public static final String RETRY_FIELD_ENROLLCOUNT = "enrollcount";
	public static final String RETRY_FIELD_MAXTRY = "maxtry";
	public static final String RETRY_FIELD_MAXTRY__AST = "maxtry_ast";
	public static final String RETRY_FIELD_MAXTRY__MISMATCH = "maxtry_mismatch";
	public static final String RETRY_FIELD_MAXTRYPROMPT = "maxtryprompt";
	public static final String RETRY_FIELD_MISMATCH__COUNT = "mismatch_count";
	public static final String RETRY_FIELD_MSG__RETRY = "msg_retry";
	public static final String RETRY_FIELD_NOINPUT = "noinput";
	public static final String RETRY_FIELD_NOINPUTPROMPT = "noinputprompt";
	public static final String RETRY_FIELD_NOMATCH = "nomatch";
	public static final String RETRY_FIELD_NOMATCHPROMPT = "nomatchprompt";
	public static final String RETRY_FIELD_PAYMENT__INVALID__RETRY = "payment_invalid_retry";
	public static final String RETRY_FIELD_POINT = "point";
	public static final String RETRY_FIELD_REPEAT__COUNT = "repeat_count";
	public static final String RETRY_FIELD_RETRY_EVENT = "retryEvent";
	public static final String RETRY_FIELD_RL__NINM__COUNT = "RL_NINM_count";
	public static final String RETRY_FIELD_TRANS__PIN__COUNT = "trans_pin_count";
	public static final String RETRY_FIELD_VERIFYCOUNT = "verifycount";
	public static final String AUTHENTICATE_VOICE_FIELD_CONFIDENCE = "confidence";
	public static final String AUTHENTICATE_VOICE_FIELD_DURATION = "duration";
	public static final String AUTHENTICATE_VOICE_FIELD_MAXTIME = "maxtime";
	public static final String AUTHENTICATE_VOICE_FIELD_SIZE = "size";
	public static final String AUTHENTICATE_VOICE_FIELD_TERMCHAR = "termchar";
	public static final String AUTHENTICATE_VOICE_FIELD_UTTERANCE = "utterance";
	public static final String AUTHENTICATE_VOICE_FIELD_VALUE = "value";
	public static final String SET_APPLICATION_STATUS_WS_FIELD_EXPECTION = "expection";
	public static final String SET_APPLICATION_STATUS_WS_FIELD_UNTITLED_1 = "untitled1";
	public static final String SET_APPLICATION_STATUS_WS_FIELD_UNTITLED_2 = "untitled2";
	public static final String DD_LAST_EXCEPTION_FIELD_ERRORCODE = "errorcode";
	public static final String DD_LAST_EXCEPTION_FIELD_MESSAGE = "message";
	public static final String DD_LAST_EXCEPTION_FIELD_OBJECT = "object";
	public static final String DD_LAST_EXCEPTION_FIELD_STACKTRACE = "stacktrace";
	public static final String DD_LAST_EXCEPTION_FIELD_TYPE = "type";
	public static final String EXIT_MENU_FIELD_CONFIDENCE = "confidence";
	public static final String EXIT_MENU_FIELD_INPUTMODE = "inputmode";
	public static final String EXIT_MENU_FIELD_INTERPRETATION = "interpretation";
	public static final String EXIT_MENU_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String EXIT_MENU_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String EXIT_MENU_FIELD_UTTERANCE = "utterance";
	public static final String EXIT_MENU_FIELD_VALUE = "value";
	public static final String TIME_FIELD_AUDIO = "audio";
	public static final String TIME_FIELD_HOUR = "hour";
	public static final String TIME_FIELD_MILLISECOND = "millisecond";
	public static final String TIME_FIELD_MINUTE = "minute";
	public static final String TIME_FIELD_SECOND = "second";
	public static final String TIME_FIELD_TIMEZONE = "timezone";
	public static final String SHAREDUUI_FIELD_ID = "id";
	public static final String SHAREDUUI_FIELD_VALUE = "value";
	public static final String VB_CONTEXT_STORE_FIELD_TRF = "TRF";
	public static final String VB_CONTEXT_STORE_FIELD_VB_ASSISTED = "vbAssisted";
	public static final String VB_CONTEXT_STORE_FIELD_VB_STATUS = "vbStatus";
	public static final String VB_CONTEXT_STORE_FIELD_VOICE_ID = "voiceID";
	public static final String VB_CONTEXT_STORE_FIELD_VOICE_INDICATOR_STATUS = "voiceIndicatorStatus";
	public static final String DYNAMIC_MENU_VAR_FIELD_AUDIO_LOCATION = "audioLocation";
	public static final String DYNAMIC_MENU_VAR_FIELD_BARGEIN = "bargein";
	public static final String DYNAMIC_MENU_VAR_FIELD_GRAMMARS = "grammars";
	public static final String DYNAMIC_MENU_VAR_FIELD_LANGUAGE = "language";
	public static final String DYNAMIC_MENU_VAR_FIELD_MAXTRIES = "maxtries";
	public static final String DYNAMIC_MENU_VAR_FIELD_MAX_TRIES_NEXT_NODE = "maxTriesNextNode";
	public static final String DYNAMIC_MENU_VAR_FIELD_NEXT_NODE = "nextNode";
	public static final String DYNAMIC_MENU_VAR_FIELD_NO_INPUT = "noInput";
	public static final String DYNAMIC_MENU_VAR_FIELD_NO_MATCH = "noMatch";
	public static final String DYNAMIC_MENU_VAR_FIELD_PROMPTS = "prompts";
	public static final String DYNAMIC_MENU_VAR_FIELD_RETRY = "retry";
	public static final String DYNAMIC_MENU_VAR_FIELD_TIME_OUT = "timeOut";
	public static final String ENROLL_WS_FIELD_AUDIO_OKCOUNT = "audioOKCount";
	public static final String ENROLL_WS_FIELD_AUDIO_SEGMENT_ID = "audioSegmentId";
	public static final String ENROLL_WS_FIELD_ENROLL_COUNT = "enrollCount";
	public static final String ENROLL_WS_FIELD_ENROLL_NO_INPUT_COUNT = "enrollNoInputCount";
	public static final String ENROLL_WS_FIELD_ENROLL_RETRY_MENU_COUNT = "enrollRetryMenuCount";
	public static final String ENROLL_WS_FIELD_ENROLL_STATUS = "enrollStatus";
	public static final String ENROLL_WS_FIELD_ENROLL_VOICE_WAV_FILE_NAME = "enrollVoiceWavFileName";
	public static final String ENROLL_WS_FIELD_ENROLL_WRONG_PHRASE_COUNT = "enrollWrongPhraseCount";
	public static final String ENROLL_WS_FIELD_EXCEPTION = "exception";
	public static final String ENROLL_WS_FIELD_IS_MAX_TRIES_EXCEEDED = "isMaxTriesExceeded";
	public static final String ENROLL_WS_FIELD_IS_SEGMENT_VALID = "isSegmentValid";
	public static final String ENROLL_WS_FIELD_PLAY_PHRASE_FILE = "playPhraseFile";
	public static final String ENROLL_WS_FIELD_REASON = "reason";
	public static final String ENROLL_WS_FIELD_REQUEST_ID = "requestId";
	public static final String ENROLL_WS_FIELD_RETRY_FLAG_ENABLED = "retryFlagEnabled";
	public static final String TRAIN_WS_FIELD_EXCEPTION = "exception";
	public static final String TRAIN_WS_FIELD_TRAIN_STATUS = "trainStatus";
	public static final String NUANCE_SERVER_STATE_FIELD_IS_NUANCE_REACHABLE = "isNuanceReachable";
	public static final String ENROLL_VOICE_PC_FIELD_CONFIDENCE = "confidence";
	public static final String ENROLL_VOICE_PC_FIELD_DURATION = "duration";
	public static final String ENROLL_VOICE_PC_FIELD_MAXTIME = "maxtime";
	public static final String ENROLL_VOICE_PC_FIELD_SIZE = "size";
	public static final String ENROLL_VOICE_PC_FIELD_TERMCHAR = "termchar";
	public static final String ENROLL_VOICE_PC_FIELD_UTTERANCE = "utterance";
	public static final String ENROLL_VOICE_PC_FIELD_VALUE = "value";
	public static final String VB_INPUTS_FIELD_AUDIO_PATH = "audioPath";
	public static final String VB_INPUTS_FIELD_CALL_FLOW_NAME = "callFlowName";
	public static final String VB_INPUTS_FIELD_DB_CONTROLLER_OBJECT = "dbControllerObject";
	public static final String VB_INPUTS_FIELD_IS_AGENT_DRIVEN_CALL = "isAgentDrivenCall";
	public static final String VB_INPUTS_FIELD_REL_ID = "relID";
	public static final String VB_INPUTS_FIELD_SEGMENT_CODE = "segmentCode";
	public static final String VB_INPUTS_FIELD_URLTYPE = "urltype";
	public static final String VB_INPUTS_FIELD_WS_URL = "wsURL";
	public static final String AUTHENTICATE_WS_FIELD_AUDIO_SEGMENT_ID = "audioSegmentId";
	public static final String AUTHENTICATE_WS_FIELD_AUTHENTICATE_COUNT = "authenticateCount";
	public static final String AUTHENTICATE_WS_FIELD_DECISION = "decision";
	public static final String AUTHENTICATE_WS_FIELD_DECISION_REASON = "decisionReason";
	public static final String AUTHENTICATE_WS_FIELD_EXCEPTION = "exception";
	public static final String AUTHENTICATE_WS_FIELD_INCONCLUSIVE_COUNT = "inconclusiveCount";
	public static final String AUTHENTICATE_WS_FIELD_IS_LOCKED = "isLocked";
	public static final String AUTHENTICATE_WS_FIELD_IS_MATCH = "isMatch";
	public static final String AUTHENTICATE_WS_FIELD_IS_NOINPUT = "isNoinput";
	public static final String AUTHENTICATE_WS_FIELD_IS_VOICE_MISMATCH = "isVoiceMismatch";
	public static final String AUTHENTICATE_WS_FIELD_NO_INPUT_COUNT = "noInputCount";
	public static final String AUTHENTICATE_WS_FIELD_REQUEST_ID = "requestID";
	public static final String AUTHENTICATE_WS_FIELD_SPEAKER_ID = "speakerID";
	public static final String DATE_FIELD_AUDIO = "audio";
	public static final String DATE_FIELD_DAYOFMONTH = "dayofmonth";
	public static final String DATE_FIELD_DAYOFWEEK = "dayofweek";
	public static final String DATE_FIELD_DAYOFWEEKNUM = "dayofweeknum";
	public static final String DATE_FIELD_DAYOFYEAR = "dayofyear";
	public static final String DATE_FIELD_MONTH = "month";
	public static final String DATE_FIELD_MONTHINYEAR = "monthinyear";
	public static final String DATE_FIELD_YEAR = "year";
	public static final String HASH_MAP_FIELD_APP_PROPERTIES = "AppProperties";
	public static final String HASH_MAP_FIELD_CALL_HISTORY = "CallHistory";
	public static final String HASH_MAP_FIELD_CUSTOMER_DETAILS = "customerDetails";
	public static final String HASH_MAP_FIELD_FLOW = "Flow";
	public static final String HASH_MAP_FIELD_INITIAL_NODE = "InitialNode";
	public static final String HASH_MAP_FIELD_LANGUAGE = "Language";
	public static final String HASH_MAP_FIELD_LINE_TYPE = "LineType";
	public static final String HASH_MAP_FIELD_MENU_HISTORY = "MenuHistory";
	public static final String HASH_MAP_FIELD_NODE = "Node";
	public static final String HASH_MAP_FIELD_PROPERTY_VALUE = "PropertyValue";
	public static final String HASH_MAP_FIELD_TRANSACTION_HISTORY = "TransactionHistory";
	public static final String SERVICEMAP_FIELD_CHANNEL = "channel";
	public static final String SERVICEMAP_FIELD_LANGUAGE = "language";
	public static final String SERVICEMAP_FIELD_LOCATION = "location";
	public static final String SERVICEMAP_FIELD_SERVICETYPE = "servicetype";
	public static final String SERVICEMAP_FIELD_TIER = "tier";
	public static final String DYNAMIC_MENU_FIELD_CONFIDENCE = "confidence";
	public static final String DYNAMIC_MENU_FIELD_INPUTMODE = "inputmode";
	public static final String DYNAMIC_MENU_FIELD_INTERPRETATION = "interpretation";
	public static final String DYNAMIC_MENU_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String DYNAMIC_MENU_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String DYNAMIC_MENU_FIELD_UTTERANCE = "utterance";
	public static final String DYNAMIC_MENU_FIELD_VALUE = "value";
	public static final String ENROLLMENU_FIELD_CONFIDENCE = "confidence";
	public static final String ENROLLMENU_FIELD_INPUTMODE = "inputmode";
	public static final String ENROLLMENU_FIELD_INTERPRETATION = "interpretation";
	public static final String ENROLLMENU_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String ENROLLMENU_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String ENROLLMENU_FIELD_UTTERANCE = "utterance";
	public static final String ENROLLMENU_FIELD_VALUE = "value";
	//}}END:PROJECT:VARIABLEFIELDS
}
