package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2021-JUN-06  09:13:58 PM
 */
public class DynamicGrammar extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for DynamicGrammar.
    */
    public DynamicGrammar() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(false);
        setFileName("");
        setMediaType("application/srgs+xml");
        setExternal(true);
        setDoNotEncodeQueryString(true);
		//}}END:CLASS:CONSTRUCTOR
    }
    
    @Override
    public String getURL() {
    	
    	String Url = mySession.getVariableField("ApplicationVariable", "PCGrammarUrl").getStringValue();
    	
    	return Url;
    }

}

